version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema
    volumes:
      - db_data:/var/lib/postgresql/data/

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: cinema
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: djangoProject1.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:password@db:5432/cinema
      MONGODB_URI: mongodb://mongo:27017/cinema

volumes:
  db_data:
  mongo_data:
